import Head from 'next/head';
import { Results, Header, Nav } from '../components';

export default function Home({ title, data, heading }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <Results
        data={JSON.parse(data)}
        heading={heading}
      />
    </>
  );
}

export async function getServerSideProps(ctx) {
  const response = await fetch(
    `https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.API_KEY}&language=en-US`
  );
  const data = await response.json();
  return {
    props: {
      title: 'Movie App',
      data: JSON.stringify(data),
      heading: 'Treding this week',
    },
  };
}
